@JWTAuth.Api_HostAddress = https://localhost:7243

### /Auth/Login (Anonymous Request)
POST {{JWTAuth.Api_HostAddress}}/Auth/Login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "user@example.com"
}

### /Auth/Refresh (Anonymous Request)
POST {{JWTAuth.Api_HostAddress}}/Auth/Refresh
Content-Type: application/json

{
  "authToken": "[AuthToken]",
  "refreshToken": "[RefreshToken]"
}

### /Auth/Revoke (Authorized Request)
DELETE {{JWTAuth.Api_HostAddress}}/Auth/Revoke
Authorization: Bearer [Token]